# Generated by Django 5.2.7 on 2025-12-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
    ]
